# Generated by Django 5.2.7 on 2026-07-20 05:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameField(
            model_name='review',
            old_name='create_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='updata_at',
            new_name='updatad_at',
        ),
        migrations.AlterField(
            model_name='course',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='Courses.category'),
        ),
    ]
