# Generated by Django 5.2.7 on 2026-07-20 07:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0002_alter_review_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='create_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='updata_at',
            new_name='updatad_at',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='updatad_at',
            new_name='updated_at',
        ),
        migrations.AlterField(
            model_name='review',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL),
        ),
    ]
